---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 14.3.37

verifier:
  name: inspec

platforms:
  - name: centos-7.6.1804

suites:
  - name: default
    run_list:
      - recipe[validatepip::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
